demo3/blog/urls.py
from . import views
from django.conf.urls import url
from . import feed

app_name = 'blog'

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'archives/(\d+)/(\d+)$',views.archives,name = 'archives'),
    # 分类路由
    url(r'category/(\d+)/$',views.category,name = 'category'),

    # 标签云  路由
    url(r'tag/(\d+)/$',views.tag,name = 'tag'),
    # rss 订阅路由
    url(r'rss/$',feed.BlogFeed(),name = 'rss'),

    url(r'^contactus/$',views.Contacts.as_view(),name='contactus'),

    #轮播图 路由
    url(r'addads/$',views.Ads.as_view(),name = 'addads'),


]

demo3/comments/urls.py
from django.conf.urls import url
from . import views
app_name = "comments"



urlpatterns = [
    url(r'^addcomment/(\d+)/$', views.AddComment.as_view(), name='addcomment' )
]

demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('blog.urls', namespace='blog')),
    url('comments/',include('comments.urls',namespace= 'comments')),
    url(r'search/', include('haystack.urls')),
]

demo3/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.

# 分类信息表
class Category(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name ='分类'
        verbose_name_plural = verbose_name


# 标签类
class Tag(models.Model):
    title = models.CharField(max_length=30)
    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "标签"
        verbose_name_plural = verbose_name


# 文章类
class Article(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    # 评论数 类型（正整数）
    views = models.PositiveIntegerField(default=0)
    # 文章类型
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    auther = models.ForeignKey(User,models.CASCADE)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '文章'
        verbose_name_plural = verbose_name


class MessageInfo(models.Model):
    username = models.CharField(max_length=20)
    email = models.EmailField(blank=True,null=True)
    subject = models.CharField(max_length=50)
    # 非Django原生类型
    info = HTMLField()




class Ads(models.Model):
    img = models.ImageField(upload_to='ads',verbose_name='广告图')
    desc = models.CharField(max_length=20,verbose_name='广告描述')
    def __str__(self):
        return self.desc

    class Meta():
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

demo3/comments/models.py
from django.db import models
from blog.models import Article
from datetime import datetime

# Create your models here.

# 文章评价表
class Comment(models.Model):
    username = models.CharField(max_length=30)
    email = models.EmailField(blank=True, null=True)
    url = models.URLField(blank=True,null = True)
    content = models.CharField(max_length=500)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.username

    class Meta():
        verbose_name = '评论'
        verbose_name_plural = verbose_name

demo3/blog/forms.py
from django import forms
from . import models

class ContactForm(forms.ModelForm):
    class Meta():
        model = models.MessageInfo
        fields = ["username","email","subject","info"]

demo3/comments/forms.py
from django import forms
from .models import Comment
class CommentForm(forms.Form):
    name = forms.CharField(required=True, label="输入名字",  widget=forms.TextInput(attrs={"id":"id_name"}) )
    email = forms.EmailField(required=True,label="输入邮箱", widget=forms.EmailInput(attrs={"id":"id_email"}))
    url = forms.URLField(label="输入个人主页", widget=forms.URLInput( attrs={"id":"id_url"}))
    comment = forms.CharField(required=True,label="输入评论",widget=forms.Textarea( attrs={"id":"id_comment"})    )

demo3/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse
from .models import Article, Category, Tag, Ads as adsModel
#  Paginator  Page
from django.core.paginator import Paginator
import markdown
from comments.forms import CommentForm
from django.views.generic import View
from .forms import ContactForm
# 分页模块 Paginator  分页器
from django.core.paginator import Paginator
import markdown
from django.conf import settings
from django.core.mail import send_mail, send_mass_mail


# Create your views here.


def index(request):
    pagenum = request.GET.get('page')
    pagenum = 1 if pagenum == None else pagenum
    # 得到所有文章         根据访问量降序排列
    articles = Article.objects.all().order_by('-views')
    paginator = Paginator(articles, 1)
    # 传入页码得到一个页面   page包含所有信息
    page = paginator.get_page(pagenum)

    return render(request, 'index.html', {'page': page})


def detail(request, id):
    # django自带的出现处理错误的方法
    article = get_object_or_404(Article, pk=id)

    # 阅读数 每点一次加1
    article.views += 1
    article.save()

    #  使用MarkDown处理body 将markdown语法转换成html标签

    # # # 第一种使用 针对需要处理的  article.body 将markdown转为html
    # article.body = markdown.markdown(article.body,extensions = [
    #     'markdown.extensions.extra',
    #     'markdown.extensions.codehilite',
    #     'markdown.extensions.toc',
    # ])
    # #
    mk = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])

    article.body = mk.convert(article.body)
    # 将markdown 中的目录赋予article对象
    article.toc = mk.toc

    # cf = CommentForm()

    return render(request, 'single.html', locals())



#  归档  显示年份和月份
def archives(request, year, month):
    # 属性__比较类型 =
    articles = Article.objects.filter(create_time__year=year, create_time__month=month)

    paginator = Paginator(articles, 1)
    # 传入页码得到一个页面   page包含所有信息
    page = paginator.get_page(1)

    return render(request, 'index.html', {'page': page})


# 分类路由
def category(request, id):
    articles = get_object_or_404(Category, pk=id).article_set.all()

    paginator = Paginator(articles, 1)
    # 传入页码得到一个页面   page包含所有信息
    page = paginator.get_page(1)

    return render(request, 'index.html', {'page': page})


# 标签云 路由
def tag(request, id):
    articles = get_object_or_404(Tag, pk=id).article_set.all()

    paginator = Paginator(articles, 1)
    # 传入页码得到一个页面   page包含所有信息
    page = paginator.get_page(1)

    return render(request, 'index.html', {'page': page})


class Contacts(View):
    def get(self, request):
        cf = ContactForm()
        return render(request, 'contact.html', locals())

    def post(self, request):
        try:
            send_mail('测试测试', '这是一封武侠邮件', settings.DEFAULT_FROM_EMAIL, ['826918436@qq.com', 'a778676681@qq.com'])
        except Exception as e:
            print(e)

        cf = ContactForm(request.POST)
        cf.save()
        cf = ContactForm()
        return render(request, 'contact.html', {"info": '成功', "cf": cf})


class Ads(View):
    def get(self, request):
        return render(request, 'addads.html')

    def post(self, request):
        img = request.FILES['img']
        desc = request.POST.get('desc')

        ad = adsModel( img = img ,desc = desc)
        ad.save()
        return redirect(reverse('blog:index'))

demo3/comments/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.views.generic import View
# Create your views here.
from django.http import HttpResponse
from .models import Comment
from blog.models import Article
from comments.forms import CommentForm


# from .forms import CommentForm


class AddComment(View):
    def post(self,request,id):
        article = get_object_or_404(Article,pk = id)
        username = request.POST.get('name')
        email = request.POST.get('email')
        url = request.POST.get('url')
        comment = request.POST.get('comment')

        c = Comment()
        c.username = username
        c.email = email
        c.url = url
        c.article = article
        c.content = comment
        c.save()

        return redirect(reverse('blog:detail',args=(id,)))

demo3/templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo3/templates/addads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加轮播图</title>
</head>
<body>
    <h2>添加轮播图</h2>

    <form action="{% url 'blog:addads' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        选择轮播图：<input type="file" name = 'img'>
        <br>
        添加描述： <input type="text" name = 'desc'>
        <br>
        <input type="submit" value="提交">
        
        
    </form>



</body>
</html>

demo3/templates/base.html
{% load extend_fun %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>   {% block title %}  {% endblock %}</title>


    <!-- meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>
<body id = 'page'>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contactus' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索" required name = 'q'>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            {% block toc %}


            {% endblock %}



            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getlatestarticles 3 as latestarticles %}
                            {% for article in latestarticles %}
                                <li><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></li>
                            {% empty %}
                            没有最新文章
                            {% endfor %}


                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getarchives as archives %}
                        {% for archive in archives %}

                        <li><a href="{% url 'blog:archives' archive.year archive.month %}">{{ archive.year }}年{{ archive.month }}月</a></li>

                            {% empty %}
                            <li>没有对象</li>
                            {% endfor %}
                    </ul>


                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategorys as categorys %}
                            {% for category in categorys %}

                        <li>
                            <a href="{% url 'blog:category' category.id %}">{{ category.title }}<span class="post-count">
                                （{{ category.article_set.count }}）</span></a>
                        </li>



                            {% empty %}
                            没有对象
                            {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {% for tag in tags %}

                         <li>
                            <a href="{% url 'blog:tag' tag.id %}">{{ tag.title }}</a>
                        </li>


                        {% empty %}
                        <li>没有对象</li>
                        {% endfor %}



                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>


        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>



</body>
</html>

demo3/templates/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="/static/css/pace.css">
	    <link rel="stylesheet" href="/static/css/custom.css">

	    <!-- js -->
	    <script src="/static/js/jquery-2.1.3.min.js"></script>
	    <script src="/static/js/bootstrap.min.js"></script>
	    <script src="/static/js/pace.min.js"></script>
	    <script src="/static/js/modernizr.custom.js"></script>


		<script src="/static/tiny_mce/tiny_mce.js"></script>
		<script type="text/javascript">
          tinyMCE.init({
              'mode':'textareas',
              'theme':'simple',
              'width': '100%' ,
              'height':100
          });
      	</script>

	</head>

	<body id="page">
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="/" data-hover="Home">首页</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">关于</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">联系</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contactus' %}" data-hover="Contact">博客</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'blog:contactus' %}" method="post" class="contact-form">
									{% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											{{ cf }}
											<button type="submit" class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>发送</span></button>
											{{ info }}
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="/static/js/script.js"></script>
		
	</body>
</html>

demo3/templates/search/indexes/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果页面</title>
</head>
<body>
    {{ query }}


    {% if query %}
        {% if page %}
            {% for article in page.object_list %}
                {{ article.object.title }}
            {% empty %}
            没有对象
            {% endfor %}
    
    
    
        {% else %}
        没有数据
        {% endif %}
    



    {% else %}
    
    {% endif %}

</body>
</html>

demo3/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果页面</title>
</head>
<body>
    <h2>搜索关键字为：{{ query }}</h2>
    <ul>


    {% if query %}
        {% if page %}
            {% for article in page.object_list %}
            <li><a href="{% url 'blog:detail' article.object.id %}">{{ article.object.title }}</a></li>

            {% empty %}
            没有对象
            {% endfor %}



        {% else %}
        没有数据
        {% endif %}




    {% else %}

    {% endif %}
</ul>
</body>
</html>

demo3/templates/single.html
{% extends 'base.html' %}




{% block left %}
<!--左边显示的文章-->



<article class="post post-{{ article.id }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ article.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ article.category.title }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ article.auther.username }}</a></span>
                            <span class="comments-link"><a href="#">{{ article.comment_set.count }}评论</a></span>
                            <span class="views-count"><a href="#">{{ article.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">

                        {{ article.body|safe }}


                    </div>
                </article>
<section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:addcomment' article.id %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>


                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for c in article.comment_set.all %}
                            <li class="comment-item">
                                <span class="nickname">{{ c.username }}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ c.create_time }}</time>
                                <div class="text">
                                    {{ c.content }}
                                </div>
                            </li>
                            {% empty %}
                            没有评论
                            {% endfor %}





                        </ul>
                    </div>
                </section>

{% endblock %}



{% block toc %}
<!--右边显示的文章目录什么的-->
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ article.toc|safe }}

                </div>
{% endblock %}