demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
# 项目路由，所有项目浏览器的请求，先进入项目路由

# 去除硬编码



urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'booktest/',include('booktest.urls')),
    url('booktest/',include('booktest.urls',namespace='booktest')),
    url('votetest/',include('votetest.urls',namespace= 'votetest')),
]

demo1/votetest/urls.py
from django.conf.urls import url
from . import views


app_name = 'votetest'


urlpatterns =[

    url(r'^index/$', views.index,name='index'),
    url(r'^list/(\d+)/$', views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),



    url(r'^login/$',views.login, name = 'login'),
    url(r'^logout/$',views.logout, name = 'logout'),
    url(r'^register/$',views.register,name = 'register'),
    url(r'^changepwd/$',views.changepwd,name = 'changepwd'),
    #激活账号  路由
    url(r'active/(.*?)/$',views.active,name = 'active'),
    #验证码路由
    url(r'^verify/$',views.verify,name = 'verify'),

    url(r'^checkuser/$',views.checkuser,name = 'checkuser'),

]

demo1/votetest/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# 标题（也就是书）
class Headline(models.Model):
    title = models.CharField(max_length=20,verbose_name='标题名')

    def __str__(self):
        return self.title



# 选项（也就是书中的角色）
class Option(models.Model):
    # 名字
    name = models.CharField(max_length=50,verbose_name= '名字')
    # 票数
    poll = models.IntegerField(verbose_name='票数')
    # 外键
    headline = models.ForeignKey(Headline,on_delete=models.CASCADE, verbose_name='标题')

    def __str__(self):
        return ('%s,%s,%s')%(self.name,self.poll,self.headline)

# 自己写的以一种方法
# # 注册用户表
# class User(models.Model):
#     name = models.CharField(max_length=30,verbose_name='用户姓名')
#     pwd = models.CharField(max_length=30,verbose_name='用户密码')
#
#     def __str__(self):
#         return ('%s,%s')%(self.name,self.pwd)


class MyUser(User):
    url = models.URLField(blank=True, null=True, default='http://www.baidu.com')
    class Meta():
        verbose_name = '用户'
        verbose_name_plural = verbose_name

demo1/votetest/forms.py
# 使用Django form 类，自动生成表单元素

from django import forms
from .models import MyUser

class LoginForm(forms.Form):
    '''
    手动构造登录表单  麻烦
    '''

    username = forms.CharField(min_length=5,max_length=10,required=True,widget=forms.TextInput,error_messages={'min_length':'不能少于5个字符','max_length':'不能大于10个字符','require':'必填项'})
    password = forms.CharField(min_length=5,max_length=10,required=True,widget=forms.PasswordInput)




class RegisterForm(forms.ModelForm):
    """
    由模型类自动生成表单
    """
    class Meta():
        model = MyUser
        fields = ['url','username']

demo1/votetest/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.template import loader
from .models import Headline,Option,User,MyUser
from .util import checklogin
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate,login as lgi,logout as lgo
# 引入表单类
from .forms import LoginForm,RegisterForm
from django.core.mail import send_mail,EmailMultiAlternatives
from django.conf import settings

from PIL import Image,ImageDraw,ImageFont
import io,random
# 引入序列化加密并且有效期信息
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,SignatureExpired


# Create your views here.



def logout(request):
    # # 自己写的第一种方法
    # del request.session['username']
    # return redirect(reverse('votetest:login'))

    # Django自带方法
    res = redirect(reverse('votetest:login'))
    lgo(request)
    return res

def login(request):

    # 自己的第一种方法
    # if request.method == 'GET':
    #     return render(request,'votetest/login.html')
    # else:
    #     username = request.POST.get("username")
    #     userpwd = request.POST.get('userpwd')
    #     try:
    #         user = User.objects.get(name=username,pwd=userpwd)
    #         res = redirect(reverse('votetest:index'))
    #         request.session['username'] = user.name
    #         return res
    #     except:
    #         return render(request,'votetest/login.html',{'error':'用户名错误'})


    #
    #   第二种方法，使用Django自带用户系统
    if request.method == "GET":
        return render(request,'votetest/login.html')

    else:
        username = request.POST.get('username')

        pwd = request.POST.get('userpwd')
        verifycode = request.POST.get('verify')

        # 如果在session中的验证码相等
        if verifycode == request.session.get('verifycode'):

            # user = authenticate(request,username = username,password = pwd)
            user = get_object_or_404(MyUser,username = username)

            # 核对用户输入密码和数据库密码（数据库密码加密，只能用用这种方式对比）

            print(user.is_active)
            if not user.is_active:
                return render(request,'votetest/login.html',{'error':'用户尚未激活'})
            else:
                check = user.check_password(pwd)
                if check:
                    lgi(request,user)
                    return redirect(reverse('votetest:index'))

                else:
                    return render(request, 'votetest/login.html', {'error': '用户名或者密码错误'})

        else:
            return render(request,'votetest/login.html',{'error':'验证码错误'})





        # # 第三种方法
        # #使用自动生成表单post
        # if request.method == 'GET':
        #     lf = LoginForm()
        #     rf = RegisterForm()
        #     return render(request,'votetest/login.html',{'lf':lf,'rf':rf})
        #
        # else:
        #     lf = LoginForm(request.POST)
        #     #如果 lf 正确有效
        #     if lf.is_valid():
        #         username = lf.cleaned_data['username']
        #         pwd = lf.cleaned_data['password']
        #         user = authenticate(request,username = username,password = pwd)
        #         if user:
        #             print(user)
        #             lgi(request,user)
        #             return redirect(reverse('votetest:index'))
        #         else:
        #             return render(request,'votetest/login.html',{'error':'用户名或密码错误'})

def register(request):
    # 自己写的第一种方法
    # if request.method == 'GET':
    #     return render(request, 'votetest/login.html')
    # else:
    #     username = request.POST.get('username')
    #     userpwd = request.POST.get('password')
    #     try:
    #         username = User.objects.get(name = username)
    #         return render(request, 'votetest/login.html', {'error': '账户或密码存在'})
    #     except:
    #         b1 = User()
    #         b1.name = username
    #         b1.pwd = userpwd
    #         b1.save()
    #         return render(request,'votetest/login.html',{'error': '注册成功！'})

#   第二种方法  Django 自带方法
    if request.method == "POST":
        username = request.POST.get('username_regi')
        pwd = request.POST.get('password_regi')
        email = request.POST.get('email')
        #在数据库创建对象
        user = MyUser.objects.create_user(username = username, password=pwd,url = 'http://xs8269.com')

        # 注册账户后，默认为非激活状态
        user.is_active = False
        user.save()
        # 第一种方法，只发送一个邮件
        # send_mail('点击激活', url, settings.DEFAULT_FROM_EMAIL,[email])


        #为了防止非人为激活用户，需要将激活地址加密
        #带有有效期的序列化
        # 得到序列化工具，默认有效期为1小时
        serutil = Serializer(settings.SECRET_KEY)
        #使用工具对字典对象序列化
        result = serutil.dumps({'userid':user.id}).decode('utf-8')
        print(result,type(result))
        # 不加decode('utf-8') 类型是 <class 'bytes'>
        # 加decode('utf-8')  类型是 <class 'str' >


        # 给邮箱发送HTMl的超链接，点开直接可以访问页面
        mail = EmailMultiAlternatives('点击激活用户',"<a href = 'http://127.0.0.1:8000/votetest/active/%s/'>点击激活</a>"%(result,),settings.DEFAULT_FROM_EMAIL,[email])
        mail.content_subtype = "html"
        mail.send()

        return render(request,'votetest/login.html',{'error':'请在一小时内激活'})




def active(request,info):
    # 序列化 并且有效期默认为1小时
    serutil = Serializer(settings.SECRET_KEY)

    try:
        obj = serutil.loads(info)
        print(obj['userid'])
        id = obj['userid']

        user = get_object_or_404(MyUser, pk=id)
        user.is_active = True
        user.save()
        return redirect(reverse('votetest:login'))


    except SignatureExpired as e:
        return HttpResponse('过期了')





def verify(request):
    # try:
    #     with open('1.png', 'wb') as f:
    #         return HttpResponse(f.readable())
    # except Exception as e:
    #     print(e)
    #     return HttpResponse("出错了")

    # 每次请求验证码，需要使用pillow构造出图像，返回
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 100
    heigth = 35
    # 创建画面对象
    im = Image.new('RGB', (width, heigth), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        # 随机取得位置
        xy = (random.randrange(0, width), random.randrange(0, heigth))
        # 随机取得颜色
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        # 填充
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    print(rand_str)
    # 构造字体对象
    font = ImageFont.truetype('cambriab.ttf', 23)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)


    # 释放画笔
    del draw
    request.session['verifycode'] = rand_str
    f = io.BytesIO()
    im.save(f, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(f.getvalue(), 'image/png')



def checkuser(request):
    if request.method == "POST":
        username = request.POST.get("username")
        print(username)
        result=MyUser.objects.filter(username = username).first()
        # result=MyUser.objects.all()
        print(result)
        if result:
            return JsonResponse({'issuccess':True})

        else:
            return JsonResponse({'issuccess':False})








# 更改密码
def changepwd(request):
    if request.method == "POST":
        username = request.POST.get('')

    else:
        return render(request,'votetest/changepwd.html',{'error':'用户名或者密码错误'})




























@checklogin
# 投票主页面
def index(request):

    allHeadline = Headline.objects.all()
    return render(request,'votetest/index.html',{'allHeadline': allHeadline})

@checklogin
# 选项列表页
def list(request,id):
    headline = None
    try:
        headline = Headline.objects.get(pk = id)
        print(headline)
    except Exception as e:
        return HttpResponse('没有选项信息')
    if request.method == 'GET':
        return render(request,'votetest/list.html',{'headline':headline})
    elif request.method == "POST":
        optionid = request.POST['button']
        option1 = Option.objects.get(pk=optionid)
        option1.poll +=1
        option1.save()

    return HttpResponseRedirect('/votetest/detail/%s' %id)

@checklogin
#  展示详情结果页
def detail(request,id):
    print(id)
    headline = Headline.objects.get(pk = id)
    # 通过投票名找选项
    name = headline.option_set.all()
# <QuerySet [<Option: 邢帅,10,邢帅和吴彦祖谁比较帅？>,
# <Option: 吴彦祖,1,邢帅和吴彦祖谁比较帅？>]>
    temp = loader.get_template('votetest/detail.html')
    result = temp.render({'name':name,'headline':headline})
    return HttpResponse(result)

demo1/templates/votetest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>






</body>
</html>

demo1/templates/votetest/changepwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>更改密码</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
<div class="container">
    <form action="#" method="post">
        请输入用户名：<input type="text" name = 'username' value = '请输入用户名'>
        <br>
        请输入新的密码：<input type="password"  name = 'password1' value = '请输入新的密码'>
        <br>
        请再次输入密码：<input type="password"  name = 'password2' value="请再次输入密码">
        <br>
        <input type="submit" value="更改">
        <br>


    </form>

</div>

</body>
</html>

demo1/templates/votetest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>展示详情结果页</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>

    <div class = 'container'>
        <h2>展示详情结果页</h2>
        {% if name %}
        {% for i in name %}
            <p>{{i.name}}--{{i.poll}}票</p>
        {% empty %}
            没有
        {% endfor %}
        {% else %}
          没有
        {% endif %}




    </div>
    <a href="{% url 'votetest:index' %}">返回主页</a>
    <br>


</body>
</html>

demo1/templates/votetest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>就让投票开始吧！！！</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h2>就让投票开始吧！！！</h2><br>
        <h3> 当前用户：{{ request.session.username }}</h3>
        <br>
        <a href="{% url 'votetest:logout' %}">退出账号</a>
        <ol>
            {% if allHeadline %}
            {% for headline in allHeadline %}
            <li><a href="{% url 'votetest:list' headline.id%}">{{headline.title}}</a></li>
            {% empty %}
            没有投票信息
            {% endfor %}

        </ol>
            {% else %}
            没有投票
            {% endif %}
    </div>



</body>
</html>

demo1/templates/votetest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>选项列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class = 'container'>


        {% if headline %}
        <form action="{% url 'votetest:list' headline.id %}" method="post">
            {% csrf_token %}
            <h2>选项列表页</h2>
            <br>
            <p>{{headline.title}}</p>
        <ol>
            {% for head in headline.option_set.all %}
                    {% if forloop.first %}
            <li><input checked type="radio" name = 'button' value='{{head.id}}'>{{ head.name }}</li>
                    {% else %}
                        <li><input type="radio" name = 'button' value='{{head.id}}'>{{ head.name }}</li>
                    {% endif %}
            {% empty %}



            <li>没有选项</li>
            {% endfor %}
            <input type="submit" value="提交">
        </ol>
        {% else %}
        没有选项信息
        {% endif %}

    <a href="{% url 'votetest:index' %}">返回主页</a>



        </form>
   </div>
</body>
</html>

demo1/templates/votetest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
    <link rel="stylesheet" href="/static/css/main.css">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</head>
<body>
<div class='container'>
    <h1>登录和注册</h1>
    {% comment %}
    被注释的内容
    <form action="{% url 'votetest:login' %}" method="post">
        {{error}}
        <br>
        用户名:<input type="text" name="username">
        <br>
        用户密码:<input type="password" name='userpwd'>
        <br>
        <input type="submit" value="提交">

    </form>
    {% endcomment %}


    {{ error }}
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">登录</a>
            </li>
            <li role="presentation"><a href="#register" aria-controls="register" role="tab" data-toggle="tab">注册</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="login">
                <form action="{% url 'votetest:login' %}" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="login1">输入登录用户名</label>
                        <input type="text" class="form-control" id="login1" placeholder="输入登录用户名" name="username">
                    </div>

                    <div class="form-group">
                        <label for="login1_pwd">输入登录密码</label>
                        <input type="password" class="form-control" id="login1_pwd" placeholder="输入登录密码" name='userpwd'>
                    </div>


                    <div class="form-group">
                        <label for="verify">输入验证码</label>
                        <input type="text" class="form-control" id="verify" placeholder="输入验证码" name='verify'>
                        <div>
                            <img src="{% url 'votetest:verify' %}" alt="丢失">
                            

                        </div>
                        
                    </div>
                    <div>
                    <button type="submit" class="btn btn-default">登录</button>

                     <span id = 'convertdata' class="btn btn-success">测试</span>
                        <div id = 'info' class = 'btn-success'>null</div>
                        <div id = 'info2'>null</div>
                    </div>

                </form>
                <a href="{% url 'votetest:changepwd' %}">忘记密码</a>
            </div>

            <script>
                $(function(){
                    $('#convertdata').click(function(){
                              <!--console.log($('#login1').val())-->
                              $.ajax({
                              url:'/votetest/checkuser/',
                              type:'post',
                              data:{'username':$('#login1').val(),

                              'csrfmiddlewaretoken':'{{ csrf_token }}'
                              },
                              success:function(data){
                                if(data.issuccess){
                                console.log('存在')
                                }else{

                                console.log('不存在')
                                }

                              }


                              })
                    })
                })






            </script>






            <div role="tabpanel" class="tab-pane" id="register">
                <form action="{% url 'votetest:register' %}" method="post">

                    <div class="form-group">
                        <label for="register1">输入注册用户名</label>
                        <input type="text" name="username_regi" class="form-control" id="register1" placeholder="输入注册用户名">
                    </div>

                    <div class="form-group">
                        <label for="register_pwd">输入注册密码</label>
                        <input type="password" name="password_regi"  class="form-control" id="register_pwd" placeholder="输入注册密码">
                    </div>

                    <div class="form-group">
                        <label for="email">输入邮箱</label>
                        <input type="text" name="email"  class="form-control" id="email" placeholder="输入邮箱">
                    </div>


                    <button type="submit" class="btn btn-default">注册</button>
                </form>
            </div>
            <br>
            <br>
            <br>

        </div>
    </div>



    {% comment %}
    <p>新方法的注册登录</p>
    <form action="#" method = 'post'>
        {{lf}}
        <br>
        <input type="submit" value="登录">

    </form>        #如果 lf 正确有效


    <form action="#" method="post">
        {{rf}}
        <input type="submit" value="注册">

    </form>
    {% endcomment %}


</div>
<br><br><br><br><br><br><br><br><br><br>

</body>
</html>

demo1/templates/votetest/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h1>注册</h1>
    <form action="{% url 'votetest:register' %}" method="post">
        {{error}}
        <br>
        用户名:<input type="text" name="username">
        <br>
        密码：<input type="password" name = 'password'>
        <input type="submit" value="提交">

    </form>
    <a href="{% url 'votetest:login' %}">去登陆</a>



    </div>

</body>
</html>