demo4/comments/urls.py
from django.conf.urls import url
from . import views
app_name = 'comments'


urlpatterns=[

    url(r'addcomment/(\d+)/$',views.AddComment.as_view(),name= 'addcomment')

]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
urlpatterns = [
    path('admin/', admin.site.urls),
    url('gametest/',include('gametest.urls',namespace= 'gametest')),
    url('comments/',include('comments.urls',namespace= 'comments')),
]

demo4/gametest/urls.py
from django.conf.urls import url
from . import views

app_name = 'gametest'

urlpatterns=[

    url(r'^single/(\d+)/$',views.Single,name='single'),

    url(r'^index/$',views.Index,name='index'),
    url(r'^about/$',views.About,name='about'),
    url(r'^games/$',views.Games,name='games'),
    url(r'^news/$',views.News,name='news'),
    url(r'^contact/$',views.Contact.as_view(),name='contact'),

    # 英雄分类
    url(r'cate/(\d+)/$',views.Cate,name = 'cate'),
    #全英雄
    url(r'^detail/$',views.Detail,name = 'detail'),

]

demo4/comments/models.py
from django.db import models
from tinymce.models import HTMLField
from gametest.models import *
# Create your models here.


# 文章评价表
class Comment(models.Model):
    username = models.CharField(max_length=30)
    email = models.EmailField(blank=True, null=True)
    url = models.URLField(blank=True,null = True)
    # 评论主题
    subject = models.CharField(max_length=30)
    content = models.CharField(max_length=500)
    heroIntro = models.ForeignKey(HeroIntro, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.username

    class Meta():
        verbose_name = '评论'
        verbose_name_plural = verbose_name

demo4/gametest/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# 图片显示轮播图
class Ads(models.Model):
    img = models.ImageField(upload_to='ads',verbose_name='广告图')
    desc = models.CharField(max_length=20,verbose_name='广告描述')
    def __str__(self):
        return self.desc

    class Meta():
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name


# 标签   （坦克，物理输出，法术输出，控制）
class Category(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name ='英雄类型分类'
        verbose_name_plural = verbose_name



# 英雄位置分类表  （上单，打野，射手，法师，辅助）
class Postion(models.Model):
    title = models.CharField(max_length=30)
    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "英雄位置标签"
        verbose_name_plural = verbose_name


# 文章英雄简介类   （英雄的介绍）
class HeroIntro(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    # 评论数 类型（正整数）
    views = models.PositiveIntegerField(default=0)
    # 英雄类型分类
    category = models.ManyToManyField(Category)
    # 英雄位置类型
    postion = models.ManyToManyField(Postion)
    author = models.ForeignKey(User,models.CASCADE)
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '英雄简介'
        verbose_name_plural = verbose_name


# 网友建议
class MessageInfo(models.Model):
    username = models.CharField(max_length=20)
    email = models.EmailField(blank=True,null=True)
    phone = models.IntegerField(max_length=20)
    city = models.CharField(max_length=20)

    subject = models.CharField(max_length=50)

    def __str__(self):
        return self.username

    class Meta():
        verbose_name = '网友建议'
        verbose_name_plural = verbose_name

demo4/comments/views.py
from django.shortcuts import render,get_object_or_404,reverse,redirect
from django.views.generic import View
from django.http import HttpResponse
from gametest.models import HeroIntro
from .models import Comment
# Create your views here.

class AddComment(View):
    def post(self,request,id):
        hero = get_object_or_404(HeroIntro,pk = id)

        name = request.POST.get('Name')
        email = request.POST.get('Email')
        subject = request.POST.get('Subject')
        content = request.POST.get('Message')

        c = Comment()
        c.username = name
        c.email = email
        c.subject = subject
        c.content = content
        c.heroIntro = hero
        c.save()
        return redirect(reverse('gametest:single',args=(id,)))

demo4/gametest/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse,HttpResponseRedirect,get_object_or_404,reverse
from .models import *
from django.views.generic import View
from django.core.mail import send_mass_mail,send_mail
from django.conf import settings
# 分页器
from django.core.paginator import Paginator

def Index(request):
    return render(request,'index.html')


def About(request):
    return render(request,'about.html')



def Games(request):
    return render(request,'games.html')




def News(request):
    return render(request,'news.html')



class Contact(View):
    def get(self,request):
        return render(request, 'contact.html')

    def post(self,request):
        m = MessageInfo()
        username = request.POST.get('username')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        city = request.POST.get('city')
        subject = request.POST.get('subject')
        send_mail('建议', subject, settings.DEFAULT_FROM_EMAIL, ['826918436@qq.com'])

        m.username = username
        m.email = email
        m.phone = phone
        m.city = city
        m.subject = subject
        m.save()

        return render(request, 'contact.html')






def Single(request,id):

    # 翻页功能
    id = int(id)
    herolist = HeroIntro.objects.all()
    print(id)
    if id < 1:
        id = len(herolist)
        hero = get_object_or_404(HeroIntro,pk = id)
        hero.views += 1
        hero.save()
        return     render(request, 'single.html', locals())
    elif id > len(herolist):
        id = 1
        hero = get_object_or_404(HeroIntro, pk=id)
        hero.views += 1
        hero.save()
        return render(request, 'single.html', locals())
    else:
        hero = get_object_or_404(HeroIntro, pk=id)
        hero.views += 1
        hero.save()

        for cate in hero.category.all():
            print(cate,type(cate.title))
        return render(request, 'single.html', locals())


# 英雄分类
def Cate(request,id):
    cate = get_object_or_404(Category,pk = id)

    catehero = cate.herointro_set.all()

    return render(request, 'category.html', locals())




def Detail(request):

    return render(request,'detail.html')

demo4/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>About</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- css -->
<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!--// css -->
<!-- font -->
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans:400,100,100italic,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //font -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.js"></script>
</head>
<body> 
<!-- banner -->
<div class="sub-banner">
		<!-- Navbar -->
		<nav class="navbar navbar-default">
			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a  href="index.html"><h1>没写完<img src="/static/images/c1.png" alt=" " />见谅</h1></a>
				</div>


				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li class="hover-effect"><a href="{% url 'gametest:index' %}">Home</a></li>
                    <li class="hover-effect active"><a href="{% url 'gametest:about' %}">About</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:games' %}">Games</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:detail' %}">Detail</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:contact' %}">Contact</a></li>
					</ul>
				</div>

			</div>
		</nav>
</div>
<!-- banner -->

<!-- about-->
	<div class="about-agileinfo" id="about">
		<div class="container">
			<h2>关于我们</h2>
			<div class="about-grids-w3-agileits">
				<div class="col-md-6 about-grid-left-agileits-w3layouts">
					<ul>
						<li><i>1.</i><a class="link link--kumya" href="{% url 'gametest:cate' 1 %}"><span data-letters="喜欢刺客，就是秒人类型的英雄？">喜欢刺客，就是秒人类型的英雄</span></a></li>
						<li><i>2.</i><a class="link link--kumya" href="{% url 'gametest:cate' 2 %}"><span data-letters="什么？你喜欢站着跟人对A？？？？">什么？你喜欢站着跟人对A？？？？</span></a></li>
						<li><i>3.</i><a class="link link--kumya" href="{% url 'gametest:cate' 3 %}"><span data-letters="你竟然别人疯狂打你，吸引火力，你好MAN哦~~">你竟然别人疯狂打你，吸引火力，你好MAN哦~~</span></a></li>
						<li><i>4.</i><a class="link link--kumya" href="{% url 'gametest:cate' 4 %}"><span data-letters="喜欢猥琐发育？后期疯狂输出？？？">喜欢猥琐发育？后期疯狂输出？？？</span></a></li>
						<li><i>5.</i><a class="link link--kumya" href="{% url 'gametest:cate' 5 %}"><span data-letters="哟，喜欢用魔法攻击别人啊？不愧是你！">哟，喜欢用魔法攻击别人啊？不愧是你！</span></a></li>
						<li><i>6.</i><a class="link link--kumya" href="{% url 'gametest:cate' 6 %}"><span data-letters="你喜欢疯狂控制别人的行动？让别人难受？666！">你喜欢疯狂控制别人的行动？让别人难受？666！</span></a></li>
					</ul>
				</div>
				<div class="col-md-6 about-grid-right-w3-agile">
					<div class="grid-w3ls">
					<figure class="effect-zoe">
						<img src="/static/images/伊泽瑞尔.jpg" alt=" " class="img-responsive" />
						<figcaption>
							<h3>Games<span>Zone</span></h3>
							<p class="icon-links">
								<a href="#"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></a>
								<a href="#"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
								<a href="#"><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span></a>
							</p>
							<p class="description">Suspendisse convallis malesuada libero, non rutrum arcu pellentesque lacinia.</p>
						</figcaption>			
					</figure>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //about -->

<!-- Collection -->
	<div class="collection-agileits">
			<div class="collection-grids-agileits-w3layouts">
				<div class="col-md-4 col-sm-4 collection-left">
					
				</div>
				<div class="col-md-8 col-sm-8 collection-right">
					<div class="col-md-4 col-sm-4 collection-grid collection-text collection-grid-1">
						<img src="/static/images/c1.png" alt="">
						<h3>Convallis </h3>
						<p>A elementum ligula lacus ac quam ultrices a scelerisque praesent vel suspendisse scelerisque.</p>
					</div>
					<div class="col-md-4 col-sm-4 collection-grid collection-image collection-grid-2">
						
					</div>
					<div class="col-md-4 col-sm-4 collection-grid collection-text collection-grid-3">
						<img src="/static/images/c2.png" alt="" />
						<h3>Lacinia</h3>
						<p>A elementum ligula lacus ac quam ultrices a scelerisque praesent vel suspendisse scelerisque.</p>
					</div>
					<div class="col-md-4 col-sm-4 collection-grid collection-image collection-grid-4">
						
					</div>
					<div class="col-md-4 col-sm-4 collection-grid collection-text collection-grid-5">
						<img src="/static/images/c3.png" alt="" />
						<h3>Sapien</h3>
						<p>A elementum ligula lacus ac quam ultrices a scelerisque praesent vel suspendisse scelerisque.</p>
					</div>
					<div class="col-md-4 col-sm-4 collection-grid collection-image collection-grid-6">
					
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
			</div>
	</div>
				<!-- //Collection -->


<!-- team -->
	<div class="team-w3layouts">
		<div class="container">
			<h3>我们的团队</h3>
			<div class="w3l_team_grids-agile">
				<div class="col-md-3 w3l_team_grid">
					<div class="view view-second">
						<img src="/static/images/邢帅.jpg" alt=" " class="img-responsive" />
						<div class="mask"></div>
						<div class="content">
							<div class="w3l_social_icons w3l_social_icons1">
								<ul>
									<li><a href="#" class="linkedin"></a></li>
									<li><a href="#" class="google"></a></li>
									<li><a href="#" class="twitter"></a></li>
									<li><a href="#" class="facebook"></a></li>
								</ul>
							</div>
							<p>主要作者：阿帅用时三天，自己动手做的作品，很垃圾，有待提高</p>
						</div>
					</div>
					<h4>邢帅</h4>
					<p>主要作者</p>
				</div>
				<div class="col-md-3 w3l_team_grid">
					<div class="view view-second">
						<img src="/static/images/陈冠希.jpg" alt=" " class="img-responsive" />
						<div class="mask"></div>
						<div class="content">
							<div class="w3l_social_icons w3l_social_icons1">
								<ul>
									<li><a href="#" class="linkedin"></a></li>
									<li><a href="#" class="google"></a></li>
									<li><a href="#" class="twitter"></a></li>
									<li><a href="#" class="facebook"></a></li>
								</ul>
							</div>
							<p>冠希哥是一位香港艺人，也是潮流的最前线，及帅气阳光时尚暴躁与一身的性格明显！</p>
						</div>
					</div>
					<h4>冠希哥</h4>
					<p>颜值担当</p>
				</div>
				<div class="col-md-3 w3l_team_grid">
					<div class="view view-second">
						<img src="/static/images/赫本.jpg" alt=" " class="img-responsive" />
						<div class="mask"></div>
						<div class="content">
							<div class="w3l_social_icons w3l_social_icons1">
								<ul>
									<li><a href="#" class="linkedin"></a></li>
									<li><a href="#" class="google"></a></li>
									<li><a href="#" class="twitter"></a></li>
									<li><a href="#" class="facebook"></a></li>
								</ul>
							</div>
							<p>想必不用多介绍了吧，赫本跟纪梵希的故事~~~~</p>
						</div>
					</div>
					<h4>奥黛丽·赫本</h4>
					<p>女神</p>
				</div>
				<div class="col-md-3 w3l_team_grid">
					<div class="view view-second">
						<img src="/static/images/giao哥.jpg" alt=" " class="img-responsive" />
						<div class="mask"></div>
						<div class="content">
							<div class="w3l_social_icons w3l_social_icons1">
								<ul>
									<li><a href="#" class="linkedin"></a></li>
									<li><a href="#" class="google"></a></li>
									<li><a href="#" class="twitter"></a></li>
									<li><a href="#" class="facebook"></a></li>
								</ul>
							</div>
							<p>giao哥风骚依旧</p>
						</div>
					</div>
					<h4>搞笑担当</h4>
					<p>Giao哥</p>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //team -->


<!-- footer -->
<div class="footer">
	<div class="container">
		<div class="col-md-3 footer-left-w3">
			<h4>联系</h4>
			<ul>
				<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></li>
				<li><a href="mailto:example@mail.com"><h6>826918436@qq.com</h6></a></li>
			</ul>
			<ul>
				<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></li>
				<li><h6>18903849270</h6></li>
			</ul>
			<ul>
				<li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></li>
				<li><h6>郑州金水西路月季花园</h6></li>
			</ul>
			<ul>
				<li><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span></li>
				<li><h6>400 820 820 820</h6></li>
			</ul>
		</div>
		<div class="col-md-5 footer-middle-w3">
			<h4>猜你喜欢</h4>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 7 %}"><img src="/static/images/锤石.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 2 %}"><img src="/static/images/诺手.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 4 %}"><img src="/static/images/金克斯.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 3 %}"><img src="/static/images/盲僧.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 12 %}"><img src="/static/images/科加斯.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 9 %}"><img src="/static/images/狐狸.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 10 %}"><img src="/static/images/剑圣.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 8 %}"><img src="/static/images/盖伦.jpg" alt=" " /></a>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="col-md-4 footer-right-w3">
			<a href="index.html"><h4>英雄 <img src="/static/images/f1.png" alt=" " /> 介绍</h4></a>
			<p>还喜欢本网站么？不喜欢也得喜欢！赶紧收藏加设为主页！</p>
			<p class="agileinfo">什么？你说很辣鸡？我心里当然有数!还用你说啊！</p>
		</div>
		<div class="clearfix"></div>
		<div class="copyright">
			<p>Copyright &copy; 2017.Company name LOL home. <a href="https://lol.qq.com/" target="_blank" title="英雄联盟之家">英雄联盟之家</a> - Collect from <a href="https://lol.qq.com/" title="网页模板" target="_blank">英雄联盟</a></p>
		</div>
	</div>
</div>
<!-- //footer -->
</body>
</html>

demo4/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Single</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- css -->
<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!--// css -->
<!-- font -->
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans:400,100,100italic,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //font -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.js"></script>
</head>
<body>
{% load extend_fun %}
<!-- banner -->
<div class="sub-banner">
		<!-- Navbar -->
		<nav class="navbar navbar-default">
			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a  href="index.html"><h1>{{ hero }}<img src="/static/images/c1.png" alt=" " /> 介绍</h1></a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li class="hover-effect"><a href="{% url 'gametest:index' %}">Home</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:about' %}">About</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:games' %}">Games</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:detail' %}">Detail</a></li>
                    <li class="hover-effect"><a href="{% url 'gametest:contact' %}">Contact</a></li>
					</ul>
				</div>

			</div>
		</nav>
</div>
<!-- banner -->
<!-- breadcrumbs -->
	<div class="agileits_breadcrumbs">
		<div class="container">
			<div class="agileits_breadcrumbs_left">
				<ul>
					<li><a href="{% url 'gametest:index' %}">Home</a><i>|</i></li>
					<li>Single</li>
				</ul>
			</div>
			<div class="agileits_breadcrumbs_right">
				<h3>Single</h3>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>




<!-- //breadcrumbs -->



<!-- single -->
	<div class="blog">
		<div class="container">
			<div class="col-md-7 wthree_blog_left">
				<div class="wthree_blog_left_grid">
					<div class="wthree_blog_left_grid_slider">
						<img src="/static/images/lol.jpg" alt=" " class="img-responsive" />
					</div>

					<h3>同类英雄</h3>
					{% if catehero %}
						{% for hero in catehero %}

						<h4><a href="{% url 'gametest:single' hero.id %}">{{ hero }}</a></h4>
					<ul>
						<li><span class="glyphicon glyphicon-user" aria-hidden="true"></span>{{ hero.author }}<i>|</i></li>
						<li><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>{{ hero.views }} 阅读<i>|</i></li>
						<li><span class="glyphicon glyphicon-tag" aria-hidden="true"></span>{{ hero.create_time }}<i></i></li>

						<p>{{ hero.body|truncatechars:10 }}....</p>
					</ul>
						{% endfor %}

					{% endif %}

				</div>


				<div class="agileits_share">
				</div>


				<div class="agileits_reply">

				</div>
				</div>




			<div class="col-md-5 wthree_blog_right">
				<div class="w3ls_search">
					<form action="#" method="post">
						<input type="text" name="Search" placeholder="还没写，别点" required="">
						<input type="submit" value=" ">
					</form>
				</div>





				<div class="w3l_archives">
					<h3>最新更新英雄</h3>
					<ul>
					{% getlatesthero as latesthero %}
						{% if latesthero %}
						{% for hero in latesthero %}


						<li><a href="{% url 'gametest:single' hero.id %}">{{ hero.title }} {{ hero.update_time }}</a></li>

					{% empty %}
						没有对象
						{% endfor %}
					{% else %}

						{% endif %}
					</ul>
				</div>



			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //single -->

<!-- footer -->
<div class="footer">
	<div class="container">
		<div class="col-md-3 footer-left-w3">
			<h4>联系</h4>
			<ul>
				<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></li>
				<li><a href="mailto:example@mail.com"><h6>826918436@qq.com</h6></a></li>
			</ul>
			<ul>
				<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></li>
				<li><h6>18903849270</h6></li>
			</ul>
			<ul>
				<li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></li>
				<li><h6>郑州金水西路月季花园</h6></li>
			</ul>
			<ul>
				<li><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span></li>
				<li><h6>400 820 820 820</h6></li>
			</ul>
		</div>
		<div class="col-md-5 footer-middle-w3">
			<h4>猜你喜欢</h4>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 7 %}"><img src="/static/images/锤石.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 2 %}"><img src="/static/images/诺手.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 4 %}"><img src="/static/images/金克斯.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile">
				<a href="{% url 'gametest:single' 3 %}"><img src="/static/images/盲僧.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 12 %}"><img src="/static/images/科加斯.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 9 %}"><img src="/static/images/狐狸.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 10 %}"><img src="/static/images/剑圣.jpg" alt=" " /></a>
			</div>
			<div class="col-md-3 img-w3-agile footer-middle-wthree">
				<a href="{% url 'gametest:single' 8 %}"><img src="/static/images/盖伦.jpg" alt=" " /></a>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="col-md-4 footer-right-w3">
			<a href="index.html"><h4>英雄 <img src="/static/images/f1.png" alt=" " /> 介绍</h4></a>
			<p>还喜欢本网站么？不喜欢也得喜欢！赶紧收藏加设为主页！</p>
			<p class="agileinfo">什么？你说很辣鸡？我心里当然有数!还用你说啊！</p>
		</div>
		<div class="clearfix"></div>
		<div class="copyright">
			<p>Copyright &copy; 2017.Company name LOL home. <a href="https://lol.qq.com/" target="_blank" title="英雄联盟之家">英雄联盟之家</a> - Collect from <a href="https://lol.qq.com/" title="网页模板" target="_blank">英雄联盟</a></p>
		</div>
	</div>
</div>

<!-- //footer -->
</body>
</html>