demo1/booktest/urls.py
from django.conf.urls import url
from . import views


# 去除硬编码
# 给应用添加命名空间
app_name = 'booktest'


urlpatterns =[
    # ^以什么什么开头，$以什么什么结尾
    url(r'^index/$', views.index,name='index'),
    url(r'^list/$', views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),

    # 删除角色
    url(r'^deletehero/(\d+)/$', views.deletehero,name = 'deletehero'),
    # 添加角色
    url(r'^addhero/(\d+)/$',views.addhero,name = 'addhero'),
#     编辑角色
    url(r'^edithero/(\d+)/$',views.edithero, name = 'edithero'),

    # 删除书
    url(r'^deletebook/(\d+)/$', views.deletebook,name = 'deletebook'),
    #添加书
    url(r'^addbook/$',views.addbook, name = 'addbook'),
    #编辑书
    url(r'^edtibook/(\d+)/$',views.edtibook,name = 'edtibook'),













]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
# 项目路由，所有项目浏览器的请求，先进入项目路由

# 去除硬编码



urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'booktest/',include('booktest.urls')),
    url('booktest/',include('booktest.urls',namespace='booktest')),
    url('votetest/',include('votetest.urls',namespace= 'votetest')),
]

demo1/booktest/models.py
from django.db import models

# Create your models here.
# 创建模型

# 一个表对应一个模型类
class BookInfo(models.Model):
    #每一个字段对应 表中的一列
    title = models.CharField(max_length=30, verbose_name='书名')
    #auto_now_add = Ture 意味着默认时间为 该行插入时间
    pub_date = models.DateTimeField(auto_now_add = True,verbose_name='发行时间')

    # 显示成中文
    def __str__(self):
        return self.title

Gender = (('man','男'),('woman','女'))

class HeroInfo(models.Model):
    name = models.CharField(max_length=30,verbose_name='姓名')
    # bool 类型性别  默认值为 True 代表男
    # gender = models.BooleanField(default=True)
    gender = models.CharField(max_length=10,choices=Gender,verbose_name='性别')

    #null = True 代表该列可以为空
    skill = models.CharField(max_length=50,null=True,verbose_name='技能')
    # ForeignKey 表名和BookInfo 为多一关系
    #book 的类型 BookInfo(对象)
    book = models.ForeignKey(BookInfo,on_delete=models.CASCADE, verbose_name='书')

    # 显示成中文
    def __str__(self):
        return self.name




# --------------------封装的方法------------------------------

# class ManageExt(models.Manager):
#     def createstmodel2(self, _title):
#         t = self.model()
#         t.title = _title
#         t.save()
#
#     def deletetestmodel2(self, _pk):
#         self.get(pk = _pk).delete()
#
#
# class TestModel(models.Model):
#     title = models.CharField(max_length=20)
#     # 添加字段 字段为模型管理器
#     objects = models.Manager()
#     #应为 manage2 继承了 manage 并且扩展了功能
#     manage2 = ManageExt()
#     #在模型类中封装方法，减少重复代码的编写
#     @classmethod
#     def createtestmodel(cls,_title):
#         t = cls(title = _title)
#         t.title = _title
#         t.save()

demo1/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse
# 加载模板
from django.template import loader
from .models import HeroInfo,BookInfo

from django.http import HttpResponseRedirect

# Create your views here.

# MVT 中的 V 可以是视图函数，也可以是视图类

# 视图接口

# 主页面
def index(request):
    # # 1 获取模板
    # template = loader.get_template('booktest/index.html')
    # # 2 构造参数字典
    # contex = {'username': 'heipi'}
    # # 3 使用模板渲染动态数据
    # result = template.render(contex)
    # #     返回
    # return HttpResponse(result)
#     新写法
    context = {'username':'黑皮'}
    return render(request,'booktest/index.html',context)

#  列表显示书籍
def list(request):
    # # 查所有书籍
    allbook = BookInfo.objects.all()
    # print(allbook)
    # # 1 获取模板
    # temp1 = loader.get_template('booktest/list.html')
    # # 2 构造参数字典,使用模板渲染动态数据
    # result = temp1.render()
    #
    # return HttpResponse(result)
    return render(request,'booktest/list.html',{'allbook': allbook})





# 显示 点击的书  中的英雄名字和技能
def detail(request,id):
    print(id)
#       id 代表书的主键,也就是英雄的外键  pk
    book = None
    try:
        # 通过id找到对应书
        book = BookInfo.objects.get(pk=id)
        print(book)
    except Exception as e:
        return HttpResponse('没有书籍信息')
#     # 1 获取模板
#     temp1 = loader.get_template('booktest/detail.html')
#     # 2 构造参数字典,使用模板渲染动态数据
#     result = temp1.render({'book':book})
#     return HttpResponse(result)
    return render(request,'booktest/detail.html',{'book':book})


# 删除角色，返回detail 和 书的id
def deletehero(request,id):
    hero = HeroInfo.objects.get(pk = id)
    bookid=hero.book.id
    hero.delete()

    return HttpResponseRedirect('/booktest/detail/%s/' %bookid)


# 删除书,返回书的list
def deletebook(request,id):
    BookInfo.objects.get(pk = id).delete()
    return HttpResponseRedirect('/booktest/list/')

# 添加书
def addbook(request):
    if request.method =='GET':
        return render(request, 'booktest/addbook.html', {})
    elif request.method == 'POST':
        book = BookInfo()
        book.title = request.POST['title']
        book.pub_date = request.POST['pub_date']
        book.save()

        return HttpResponseRedirect('/booktest/list')



# 添加角色
def addhero(request,id):
    if request.method == 'GET':
        return render(request, 'booktest/addhero.html',{'bookid':id})

    elif request.method == 'POST':
        book = BookInfo.objects.get(pk = id)

        hero = HeroInfo()
        hero.name = request.POST['username']
        hero.gender = request.POST['sex']
        hero.skill = request.POST['skill']
        hero.book = book
        hero.save()


        return HttpResponseRedirect('/booktest/detail/%s/'%(id,))

# 编辑书籍
def edtibook(request,id):
    book = BookInfo.objects.get(pk = id)

    if request.method == 'GET':
        return render(request,'booktest/editbook.html',{'book':book})

    elif request.method == 'POST':
        book.title = request.POST['title']
        book.pub_date = request.POST['pub_date']
        book.save()

        return HttpResponseRedirect('/booktest/list/')




# 编辑英雄
def edithero(request,id):
    hero = HeroInfo.objects.get(pk = id)

    if request.method == 'GET':

        return render(request, 'booktest/edithero.html', {'hero': hero})

    elif request.method == 'POST':

        hero.name = request.POST['username']
        hero.gender = request.POST['sex']
        hero.skill = request.POST['skill']
        hero.save()

        return HttpResponseRedirect('/booktest/detail/%s/'%(hero.book.id,))

demo1/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class = 'container'>
    <h2>添加书籍</h2>
        <form action="{% url 'booktest:addbook' %}" method="post">
            书名:<input type="text" name = 'title'>
            <hr>
            发行时间:<input type="text" name = 'pub_date'>
            <hr>
            <input type="submit" value="提交">
            <hr>

        </form>

    </div>

</body>
</html>

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加角色</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <div class = 'container'>
        <h2>添加角色</h2>
        <form action="{% url 'booktest:addhero' bookid %}" method="post">
            书id：<input type="text" disabled value="{{bookid}}">
            <hr>
            角色名：<input type = 'text' name = 'username'>
            <hr>
            {# Radio Button 单选框#}
            性别：<input type = 'radio' name = 'sex' value="man">男<input type="radio" name = 'sex' value="woman">女
            <hr>
            绝招：<input type="text" name = 'skill'>
            <hr>
            <input type="submit" value="提交">
            <hr>
        </form>


    </div>




</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>

        <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class = 'container'>
        <h2>详情页</h2>
    <br>
    {% if book %}
    <h3>{{ book.title }}</h3>
    <ul>
        {% for hero in book.heroinfo_set.all %}
        <li>{{ hero.name }}---{{hero.gender}}--{{hero.skill}}
            <a href="{% url 'booktest:deletehero' hero.id %}">删除</a>
            <a href="{% url 'booktest:edithero' hero.id %}">编辑角色</a>
        </li>
        {% empty %}
            <li>没有角色</li>
        {% endfor %}
        <a href="{% url 'booktest:addhero' book.id %}">添加角色</a>
        <br>


    </ul>

    {% else %}
    没有书籍信息
    {% endif %}


    </div>



    {# <a href="/booktest/list/">返回列表页</a> #}
    <a href="{% url 'booktest:list' %}" >返回列表页</a>
</body>
</html>

demo1/templates/booktest/edithero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄</title>
    <link rel="stylesheet" href="/static/css/main.css">

<body>
    <div class = 'container'>
        <h2>编辑英雄</h2>
        <form action="{% url 'booktest:edithero' hero.id %}" method="post">
            英雄id：<input type="text" disabled placeholder="{{hero.id}}">
            <hr>
            角色名：<input type = 'text' name = 'username' placeholder="{{hero.name}}">
            <hr>
            性别：
            {% if hero.gender == 'man' %}
            <input type = 'radio' name = 'sex' value="man" checked>男<input type="radio" name = 'sex' value="woman">女
            {% else %}
            <input type = 'radio' name = 'sex' value="man">男<input type="radio" name = 'sex' value="woman" checked>女
            {%  endif %}
            {# Radio Button 单选框#}

            <hr>
            绝招：<input type="text" name = 'skill' placeholder='{{hero.skill}}'>
            <hr>
            <input type="submit" value="提交">
            <hr>
        </form>


    </div>




</body>
</html>

demo1/templates/booktest/edtibook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class = 'container'>
    <form action="{% url 'booktest:editbook' book.id %}">
    <input type="text" name = 'title' placeholder="{{book.title}}">
        <br>
        <input type="text" name = 'pub_date' placeholder="{{book.pub_date}}">
    </form>


    </div>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" ></script>
        <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">

        <h2>首页</h2>
    {{ username }}
    <br>
    {# <a href="/booktest/list/">进入列表页</a> #}
    <a href="{% url 'booktest:list' %}">进入列表页</a>





<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/static/img/hot1.jpg" alt="加载错误">
      <div class="carousel-caption">
      </div>

    </div>
    <div class="item">

      <img src="/static/img/hot2.jpg" alt="加载错误">
      <div class="carousel-caption">
      </div>
    </div>

    <div class="item">
      <img src="/static/img/hot3.jpg" alt="加载错误">
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
          <img src="/static/img/hot4.jpg" alt="加载错误">
          <div class="carousel-caption">
          </div>
    </div>


  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>
</div>
    <!--自动翻页，1000毫秒一次-->
    <script>
        $('.carousel').carousel({
  interval: 1000
})
    </script>


</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
        <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>


    <div class ='container'>
        <h2>列表页</h2>
        <ul>
        {% if allbook %}
        {% for book in allbook %}
            {# <li><a href="/booktest/detail/{{book.id}}/">{{ book.title }}</a></li> #}
            <li><a href="{% url 'booktest:detail' book.id %}">{{ book.title }}---{{ book.pub_date }}</a>
            <a href="{% url 'booktest:deletebook' book.id %}">删除</a>
                <br>
                <a href="{% url 'booktest:edtibook' book.id %}">编辑</a>
            </li>

        {% empty %}
            没有书籍信息
        {% endfor %}
    </ul>

    {% else %}
        没有书
    {% endif %}
    </div>

    <br>
    <a href="{% url 'booktest:addbook' %}">添加书籍</a>
    <br>
    {# <a href="/booktest/index/">去主页</a> #}
    <a href="{% url 'booktest:index' %}">去主页</a>

</body>
</html>